pub(super) fn shell_copy() -> super::ShellCopy {
    super::ShellCopy {
                app_name: "Agent Taskboard".into(),
                register_first_project: "Register the first Project".into(),
                pair_another_host: "Pair another Host".into(),
                no_project_title: "No Project on this Host yet".into(),
                no_project_body: "Register a local folder and pick an Issue Tracker.".into(),
                quit_host: "Quit Host".into(),
                show_window: "Open window".into(),
                settings: "Settings".into(),
                updates: "App updates".into(),
                check_for_updates: "Check for updates".into(),
                update_checking: "Checking…".into(),
                update_available: "Update available".into(),
                update_ready: "A new version is ready. Nothing downloads or installs until you confirm.".into(),
                update_notes: "Release notes".into(),
                update_confirm: "Download and install".into(),
                update_later: "Later".into(),
                update_current: "You already have the latest version.".into(),
                update_unavailable_browser: "A browser Client cannot replace a Host installation. Check from the desktop app on that machine.".into(),
                update_active_runs: "An active Run is still running, so the update cannot be installed. End or stop every Run first.".into(),
                update_installing: "Downloading and installing…".into(),
                update_failed: "The update failed. Host data and Client settings were not changed.".into(),
                language: "Interface language".into(),
                theme: "Theme".into(),
                language_zh: "简体中文".into(),
                language_en: "English".into(),
                theme_warm_paper: "Warm paper".into(),
                theme_plain_paper: "Plain paper".into(),
                theme_plain_night: "Plain night".into(),
                hosts: "Host".into(),
                projects: "Project".into(),
                this_machine: "This machine".into(),
                shade_light: "Light".into(),
                shade_dark: "Dark".into(),
                edit_menu: "Edit".into(),
                pairing_required: "Access via Tailscale, LAN, or another site needs a long-term token. The loopback page at http://127.0.0.1:10529/ does not require pairing.".into(),
                pairing_title: "Pairing".into(),
                pairing_this_host: "Let others join this Host".into(),
                pairing_to_another: "Connect to another Host".into(),
                pairing_address: "Reachable address".into(),
                pairing_show: "Show pairing code".into(),
                pairing_copy: "Copy".into(),
                pairing_same_payload: "The QR code and the copyable text are the same payload. Reach this Host on your own Tailscale, LAN, or VPN — there is no product relay.".into(),
                pairing_paste: "Paste pairing payload".into(),
                pairing_connect: "Connect".into(),
                paired_clients: "Paired clients".into(),
                revoke_client: "Revoke".into(),
                no_paired_clients: "No paired clients yet.".into(),
                add_project: "Register Project".into(),
                edit_project: "Edit registration…".into(),
                remove_project: "Remove Project…".into(),
                register_project_title: "Register Project".into(),
                edit_project_title: "Edit Project registration".into(),
                display_name: "Display name".into(),
                local_directory: "Local directory".into(),
                choose_directory: "Choose folder".into(),
                choose_directory_desktop_only: "The system folder picker is only available in the desktop window on this machine. In a browser Client, paste an absolute path on the Host.".into(),
                inferring_from_directory: "Inferring from the local directory…".into(),
                inference_failed: "No usable GitHub remote was found in this directory. Enter the repository manually.".into(),
                active_project_edit_hint: "This Project has an active Run. Only the display name can be changed; stop all active Runs before changing its directory or GitHub connection.".into(),
                remote_project_hint: "Enter an absolute path on the remote Host. Confirm it on that Host or paste it manually; this Client will not choose a local folder.".into(),
                operation_pending: "Saving…".into(),
                inference_pending: "Inferring…".into(),
                retry_inference: "Retry inference".into(),
                removal_pending: "Removing…".into(),
                github_host: "GitHub host".into(),
                repository: "Repository".into(),
                infer_from_directory: "Infer from local directory".into(),
                use_inference: "Use this inference".into(),
                inference_hint: "After you choose a local directory, the display name defaults to the folder name. The GitHub connection appears as a candidate and is adopted only after confirmation; manual values always remain valid.".into(),
                save_registration: "Save registration".into(),
                cancel: "Cancel".into(),
                remove_confirm_title: "Remove this Project?".into(),
                remove_confirm_body: "This only unregisters it on this Host. It does not delete the local directory, git repository, or remote Issues.".into(),
                remove_confirm: "Remove registration only".into(),
                cannot_remove_active_run: "Cannot remove now".into(),
                cannot_remove_active_run_body: "This Project has an active Run. Stop or finish the Run first. Closing a Client or switching Project does not stop the Run.".into(),
                remove_keep_claims_body: "This Project has execution-stopped issues. Removing only unregisters it here; Tracker claims are not released.".into(),
                continue_run: "Continue".into(),
                release_claim: "Release claim".into(),
                execution_stopped: "Execution stopped".into(),
                waiting: "Waiting".into(),
                running: "Running".into(),
                inject_line: "Inject".into(),
                inject_placeholder: "Inject a line".into(),
                notify_desktop: "Desktop notifications".into(),
                notify_sound: "Notification sound".into(),
                notify_waiting: "Waiting for you".into(),
                notify_completed: "Run finished".into(),
                notify_abnormal: "Run stopped abnormally".into(),
                notify_crash: "Recovered after Host crash".into(),
                got_it: "Got it".into(),
                auth_failed: "GitHub credentials for this Project are not available.".into(),
                connection_unavailable: "This Project cannot reach GitHub right now.".into(),
                repair_cli: "Sign in with gh".into(),
                repair_secrets: "Write a PAT for this host in the Host secrets file".into(),
                repair_env: "Set the app-specific or generic environment variable".into(),
                no_gh_detected: "gh was not detected on this machine.".into(),
                connection_ready: "GitHub is connected".into(),
                project_menu: "Manage".into(),
                board_hint: "Blocked → Frontier → In progress → Recently closed. Closing is not drag.".into(),
                child_hint: "Direct children only. Still a board, not a second Frontier.".into(),
                graph_hint: "In overview, click an Issue to make it the center. In focused mode, clicking a node only changes details. Dependencies only — not parent/child.".into(),
                view_board: "Board".into(),
                view_graph: "Dependency graph".into(),
                view_dependencies: "View dependency graph".into(),
                graph_overview: "Dependency graph overview".into(),
                graph_return_overview: "Return to dependency graph overview".into(),
                graph_truncated: "Showing {shown}/{total} open Issues; Dependency participants are retained first by a stable rule.".into(),
                graph_no_dependencies: "These open Issues have no Dependencies between them.".into(),
                show_closed_context: "Also show closed context".into(),
                graph_center: "Center Issue: {issue}".into(),
                graph_center_here: "Expand from here".into(),
                graph_show_complete: "View complete upstream and downstream ({count} Issues)".into(),
                graph_show_neighborhood: "Collapse to one hop".into(),
                graph_show_more: "Show more nodes".into(),
                graph_canvas_limit: "Canvas shows {shown}/{total}; search the complete relationship list for the rest.".into(),
                graph_complete_list: "Complete relationship list".into(),
                graph_search_placeholder: "Search upstream and downstream Issues".into(),
                graph_upstream: "Upstream".into(),
                graph_downstream: "Downstream".into(),
                graph_both: "Both".into(),
                clear_filter: "Clear filter".into(),
                col_blocked: "Blocked".into(),
                col_frontier: "Frontier".into(),
                col_in_progress: "In progress".into(),
                col_recent: "Recently closed".into(),
                no_items: "None".into(),
                no_frontier_blocked: "Nothing to claim. The rest are still blocked.".into(),
                no_frontier_claimed: "Nothing to claim. Open issues are already claimed.".into(),
                no_frontier_empty: "Nothing to claim. This Project has no open issues.".into(),
                no_recent: "None just closed".into(),
                recent_note: "Only the last few, not all closed issues. Dragging here does not close.".into(),
                empty_no_data: "No displayable data yet.".into(),
                empty_incomplete: "Issue data could not be read completely. Frontier and the dependency graph are hidden to prevent incorrect decisions.".into(),
                empty_tracker_error: "The Tracker returned a business error. Frontier and the dependency graph are hidden to avoid decisions based on stale data.".into(),
                issue_document: "Issue document".into(),
                issue_document_loading: "Loading the Issue document…".into(),
                issue_document_retry: "Retry load".into(),
                issue_document_stale: "The document could not be refreshed. Showing the last read-only copy from".into(),
                issue_document_failed: "The document has never loaded successfully.".into(),
                family: "Parent and child Issues".into(),
                deps: "Dependencies".into(),
                parent: "Parent Issue".into(),
                children: "Child Issues".into(),
                no_parent: "None".into(),
                no_kids: "None".into(),
                only_kids: "Only these children".into(),
                blocked_by: "Blocked by these Issues".into(),
                blocking: "Blocks these Issues".into(),
                none_block: "None".into(),
                none: "None".into(),
                claimed: "Claimed".into(),
                unclaimed: "Unclaimed".into(),
                pick_issue: "Select an Issue".into(),
                recent_limit: "Recently-closed count".into(),
                recent_limit_help: "Default 5. Only the rightmost column. Dragging here does not close.".into(),
                refresh_interval: "Auto-refresh interval (seconds)".into(),
                refresh_interval_help: "While someone is looking at this board, pull Tracker on this interval. Default 300 seconds, minimum 15 seconds, with no maximum.".into(),
                unclear_issue: "The other side is unclear".into(),
                refresh_now: "Refresh".into(),
                refresh_refreshing: "Refreshing".into(),
                refresh_as_of: "Data as of".into(),
                refresh_next: "Next refresh".into(),
                refresh_offline: "Offline".into(),
                refresh_offline_recovery: "Check the network on the computer running the Host, then select Refresh to retry.".into(),
                refresh_never: "Tracker has never been fetched successfully.".into(),
                refresh_rate_limited: "Rate limited".into(),
                refresh_retry: "Can retry around".into(),
                refresh_paused: "Auto-refresh is paused. You can try again manually.".into(),
                refresh_auth: "Credentials unavailable".into(),
                refresh_auth_recovery: "Update the GitHub credentials on the computer running the Host, then select Refresh to retry.".into(),
                refresh_incomplete: "Incomplete data".into(),
                refresh_tracker_error: "Tracker business error".into(),
                new_run: "New".into(),
                execute_run: "Run".into(),
                start_run: "Start".into(),
                start_run_pending: "Starting…".into(),
                switch_agent: "Switch Agent".into(),
                pick_agent: "Choose Agent".into(),
                no_agent_selected: "No Agent selected".into(),
                next_step: "Next".into(),
                launch_title: "Launch".into(),
                prefill_current: "Prefill is this Project's last successful launch. You can change it this time.".into(),
                prefill_other: "Prefill is this Agent's memory from another Project. You can change it this time.".into(),
                prefill_seed: "Prefill is the local CLI seed. You can change it this time.".into(),
                isolation: "Isolated work directory".into(),
                isolation_off_reason: "Why it's unavailable".into(),
                isolation_hint: "This uses a git worktree. It stays off and is not remembered.".into(),
                run_intent: "Run intent".into(),
                intent_none: "None".into(),
                intent_modify: "Modify".into(),
                intent_continue: "Continue".into(),
                intent_answer: "Answer only".into(),
                intent_review: "Review".into(),
                intent_custom: "Custom".into(),
                opening_placeholder: "What should the Agent do".into(),
                folded_options: "Extra options".into(),
                command_preview: "Command preview".into(),
                show_command_preview: "Show command preview".into(),
                instruction_required: "Tell the Agent what to do.".into(),
                working_directory: "Working directory".into(),
                unbound_issue: "Unbound Issue".into(),
                stop_run: "Stop".into(),
                quit_active_title: "Active Runs still running".into(),
                quit_active_body: "Quitting Host will stop every active Run. Go back to keep them running.".into(),
                quit_return: "Go back".into(),
                quit_stop_all: "Stop all".into(),
                view_changes: "View changes".into(),
                focus_run: "Focus".into(),
                open_issue: "Open in browser".into(),
                search_title: "Search Issues".into(),
                search_placeholder: "Search titles on Enter".into(),
                search_all_triage: "All triage".into(),
                search_all_states: "open / closed".into(),
                search_open: "open".into(),
                search_closed: "closed".into(),
                search_submit: "Search".into(),
                keyboard_help: "Keyboard help".into(),
                keyboard_help_body: "Use J / K or arrow keys to move between board cards; Enter opens details; / focuses search; ? opens or closes help; Escape closes help. When the terminal is focused, all shortcuts stay with the official TUI.".into(),
                this_round: "This round".into(),
                uncommitted: "Uncommitted".into(),
                add_change_note: "Add a change note".into(),
                change_note_placeholder: "One sentence. It goes into the next opening.".into(),
                delete_change_note: "Delete note".into(),
                auto_advance: "Auto-advance".into(),
                auto_advance_help: "Host master switch. A Project still has to turn it on before the next ready-for-agent is claimed.".into(),
                project_auto_advance: "Auto-advance this Project".into(),
                restore_auto_advance: "Restore auto-advance after cold start".into(),
                restore_delay: "Seconds to wait after cold start".into(),
                pending_confirmation: "Pending confirmation: about to claim the next ready-for-agent".into(),
                veto_advance: "Veto".into(),
                usage: "Usage".into(),
                usage_hint: "Token traffic for every Project on this Host. No dollar estimates and no account quotas.".into(),
                host_overview: "Overview".into(),
                host_overview_hint: "Project status and Runs on the current Host; Runs are grouped by terminal state.".into(),
                host_overview_empty: "No Runs have been started through Agent Taskboard yet; Project status remains visible above.".into(),
                return_to_board: "Back to board".into(),
                show_sidebar: "Show sidebar".into(),
                hide_sidebar: "Hide sidebar".into(),
                show_issue_detail: "Show details".into(),
                hide_issue_detail: "Hide details".into(),
                show_ended_runs: "Show ended Runs".into(),
                run_group_waiting: "Waiting".into(),
                run_group_running: "In progress".into(),
                run_group_stopped: "Execution stopped".into(),
                run_group_ended: "Ended".into(),
                range_24_hours: "24 hours".into(),
                range_today: "Today".into(),
                range_7_days: "7 days".into(),
                range_30_days: "30 days".into(),
                range_custom: "Custom".into(),
                filter_all: "All".into(),
                filter_project: "Project".into(),
                filter_agent: "Agent".into(),
                filter_model: "Model".into(),
                token_input: "input".into(),
                token_output: "output".into(),
                token_cache_read: "cache read".into(),
                token_cache_write: "cache write".into(),
                token_reasoning: "reasoning".into(),
                token_total: "total".into(),
                ttft: "TTFT".into(),
                gen_rate: "Generation rate".into(),
                cache_hit: "Cache hit".into(),
                spike: "Slow".into(),
                proxy_disclaimer: "The board does not manage Clash or other proxies. If the path is jittery, change nodes in your own proxy tool.".into(),
                open_host_usage: "Host usage ↗".into(),
                open_this_run: "Open this Run terminal ↗".into(),
                lane_main: "Main".into(),
                lane_subagent: "Subagent".into(),
                lane_switched: "Retired".into(),
                usage_empty: "No Run usage in this window.".into(),
                close_usage: "Back to board".into(),
                mobile_switch_scope: "Switch scope".into(),
                mobile_board: "Board".into(),
                mobile_issue: "Issue".into(),
                mobile_run: "Run".into(),
                mobile_recent_output: "Recent output".into(),
                mobile_live_terminal: "Open live terminal".into(),
                create_issue: "Create Issue".into(),
                edit_issue: "Edit Issue".into(),
                save_issue: "Save Issue".into(),
                issue_title: "Title".into(),
                issue_body: "Body".into(),
                add_comment: "Add comment".into(),
                comment_placeholder: "Write a comment".into(),
                parent_issue: "Parent Issue".into(),
                dependency_blockers: "Blocked by".into(),
                clear_dependency: "Clear Dependency".into(),
                save_relations: "Save relationship".into(),
                close_issue: "Close Issue".into(),
                reopen_issue: "Reopen Issue".into(),
                issue_updates: "Comments and relationships".into(),
    }
}
