pub(super) fn shell_copy() -> super::ShellCopy {
    super::ShellCopy {
        app_name: "Agent Taskboard".into(),
                register_first_project: "登记第一个 Project".into(),
                pair_another_host: "配对另一个 Host".into(),
                no_project_title: "这台 Host 上还没有 Project".into(),
                no_project_body: "先登记一个本地目录，并选好 Issue Tracker。".into(),
                quit_host: "退出 Host".into(),
                show_window: "打开窗口".into(),
                open_web_page: "打开网页".into(),
                settings: "设置".into(),
                updates: "应用更新".into(),
                check_for_updates: "检查更新".into(),
                update_checking: "正在检查…".into(),
                update_available: "发现新版本".into(),
                update_ready: "有新版本可安装。确认后才会下载和安装。".into(),
                update_notes: "版本说明".into(),
                update_confirm: "下载并安装".into(),
                update_later: "稍后".into(),
                update_current: "已经是最新版本。".into(),
                update_unavailable_browser: "浏览器 Client 不能给 Host 换包。请在本机桌面应用中检查更新。".into(),
                update_active_runs: "还有活跃 Run，不能安装更新。请先让全部 Run 结束或停止。".into(),
                update_installing: "正在下载并安装…".into(),
                update_failed: "更新失败，Host 数据和 Client 设置都没有改变。".into(),
                language: "界面语言".into(),
                language_zh: "简体中文".into(),
                language_en: "English".into(),
                hosts: "Host".into(),
                projects: "Project".into(),
                this_machine: "本机".into(),
                edit_menu: "编辑".into(),
                window_menu: "窗口".into(),
                help_menu: "帮助".into(),
                edit_undo: "撤销输入".into(),
                edit_redo: "重做输入".into(),
                edit_cut: "剪切".into(),
                edit_copy: "复制".into(),
                edit_paste: "粘贴".into(),
                edit_select_all: "全选".into(),
                usage_guide: "使用说明".into(),
                pairing_required: "经 Tailscale、局域网或其它站点访问需要长期令牌。本机回环页 http://127.0.0.1:10529/ 免配对。".into(),
                pairing_title: "配对".into(),
                pairing_this_host: "让别人连这台".into(),
                pairing_to_another: "连到另一台 Host".into(),
                pairing_address: "可到达地址".into(),
                pairing_show: "出示配对码".into(),
                pairing_copy: "复制".into(),
                pairing_same_payload: "二维码和复制文本是同一份信息。连通走你自己的 Tailscale、局域网或 VPN，没有产品中继。".into(),
                pairing_paste: "粘贴配对信息".into(),
                pairing_connect: "连接".into(),
                paired_clients: "已配对的 Client".into(),
                revoke_client: "撤销".into(),
                no_paired_clients: "还没有已配对的 Client。".into(),
                add_project: "登记 Project".into(),
                edit_project: "编辑登记…".into(),
                remove_project: "移除 Project…".into(),
                register_project_title: "登记 Project".into(),
                edit_project_title: "编辑 Project 登记".into(),
                display_name: "显示名称".into(),
                local_directory: "本地目录".into(),
                choose_directory: "选择目录".into(),
                choose_directory_desktop_only: "系统目录选择只在本机桌面窗口可用。浏览器 Client 请手动粘贴 Host 上的绝对路径。".into(),
                inferring_from_directory: "正在从本地目录推断…".into(),
                inference_failed: "这个目录没有可用的 GitHub remote，请手动填写仓库。".into(),
                active_project_edit_hint: "这个 Project 有活跃 Run，只能修改显示名称；要改目录或 GitHub 连接，请先停止所有活跃 Run。".into(),
                remote_project_hint: "这里填写远程 Host 上的绝对路径。请在远程 Host 上确认目录，或手动粘贴该路径；不会选择这台 Client 上的目录。".into(),
                operation_pending: "保存中…".into(),
                inference_pending: "推断中…".into(),
                retry_inference: "重试推断".into(),
                removal_pending: "移除中…".into(),
                github_host: "GitHub host".into(),
                repository: "仓库".into(),
                infer_from_directory: "从本地目录推断".into(),
                use_inference: "使用这份推断结果".into(),
                inference_hint: "选好本地目录后，显示名称默认用目录名；GitHub 连接会作为候选显示，确认后才采纳。手工填写始终有效。".into(),
                save_registration: "保存登记".into(),
                cancel: "取消".into(),
                remove_confirm_title: "移除这个 Project？".into(),
                remove_confirm_body: "只取消这台 Host 上的登记。不会删除本地目录、git 仓库，也不会删除远端 Issue。".into(),
                remove_confirm: "只移除登记".into(),
                cannot_remove_active_run: "现在不能移除".into(),
                cannot_remove_active_run_body: "这个 Project 有活跃 Run。先停止或结束 Run，再回来移除。关闭 Client 或切换 Project 都不会停止 Run。".into(),
                remove_keep_claims_body: "这个 Project 有执行已停的票。移除只取消本机登记，Tracker 上的认领不会自动释放。".into(),
                continue_run: "继续".into(),
                release_claim: "释放认领".into(),
                execution_stopped: "执行已停".into(),
                waiting: "等待操作".into(),
                running: "运行中".into(),
                inject_line: "注入".into(),
                inject_placeholder: "注入一行".into(),
                notify_desktop: "桌面通知".into(),
                notify_sound: "通知声音".into(),
                notify_waiting: "等待操作".into(),
                notify_completed: "Run 已正常完成".into(),
                notify_abnormal: "Run 异常停止".into(),
                notify_crash: "Host 崩溃后已捡回".into(),
                got_it: "知道了".into(),
                auth_failed: "这个 Project 的 GitHub 凭据不可用。".into(),
                connection_unavailable: "这个 Project 暂时连不上 GitHub。".into(),
                repair_cli: "用 gh 登录".into(),
                repair_secrets: "在 Host 秘密文件里写入这个 host 的 PAT".into(),
                repair_env: "设置应用专用或通用环境变量".into(),
                no_gh_detected: "这台电脑上没检测到 gh。".into(),
                connection_ready: "GitHub 已连通".into(),
                project_menu: "管理".into(),
                board_hint: "从左到右：阻塞中 → Frontier → 进行中 → 最近完成。不能拖列关票。".into(),
                child_hint: "只看这些直接子票。仍是看板视图，不是第二种 Frontier。".into(),
                graph_hint: "概览点击 Issue 设为中心；中心模式点节点只换详情。只画 Dependency，不画父子。".into(),
                view_board: "看板".into(),
                view_graph: "依赖图".into(),
                view_dependencies: "查看依赖图".into(),
                graph_overview: "依赖图概览".into(),
                graph_return_overview: "返回依赖图概览".into(),
                graph_truncated: "仅显示 {shown}/{total} 个未关闭 Issue；已按稳定规则优先保留 Dependency 参与者。".into(),
                graph_no_dependencies: "这些未关闭 Issue 之间没有 Dependency。".into(),
                show_closed_context: "也显示已关闭上下文".into(),
                graph_center: "中心 Issue：{issue}".into(),
                graph_center_here: "从此处展开".into(),
                graph_show_complete: "查看完整上下游（{count} 个 Issue）".into(),
                graph_show_neighborhood: "收起到一跳上下游".into(),
                graph_show_more: "继续显示节点".into(),
                graph_canvas_limit: "画布显示 {shown}/{total}；其余 Issue 可在完整关系列表中搜索。".into(),
                graph_complete_list: "完整关系列表".into(),
                graph_search_placeholder: "搜索上下游 Issue".into(),
                graph_upstream: "上游".into(),
                graph_downstream: "下游".into(),
                graph_both: "上下游".into(),
                clear_filter: "清除过滤".into(),
                col_blocked: "阻塞中".into(),
                col_frontier: "Frontier".into(),
                col_in_progress: "进行中".into(),
                col_recent: "最近完成".into(),
                no_items: "没有".into(),
                no_frontier_blocked: "没有可领的票。剩下的都还被挡住。".into(),
                no_frontier_claimed: "没有可领的票。未关的都已被认领。".into(),
                no_frontier_empty: "没有可领的票。这个 Project 里没有未关的票。".into(),
                no_recent: "还没有刚关的".into(),
                recent_note: "只留最近几张，不是全部已关闭。不能拖进这一列来关票。".into(),
                empty_no_data: "还没有可显示的数据。".into(),
                empty_incomplete: "Issue 数据没有完整读完。为避免误判，暂不显示 Frontier 和依赖图。".into(),
                empty_tracker_error: "Tracker 返回业务错误。为避免使用过期数据误判，暂不显示 Frontier 和依赖图。".into(),
                issue_document: "Issue 正文".into(),
                issue_document_loading: "正在读取 Issue 正文…".into(),
                issue_document_retry: "重试读取".into(),
                issue_document_stale: "正文读取失败；以下为只读的上次内容，数据截至".into(),
                issue_document_failed: "正文尚未成功读取。".into(),
                family: "父子关系".into(),
                deps: "依赖关系".into(),
                parent: "父 Issue".into(),
                children: "子 Issue".into(),
                no_parent: "无".into(),
                no_kids: "无".into(),
                only_kids: "只看这些子票".into(),
                blocked_by: "被这些 Issue 阻塞".into(),
                blocking: "会阻塞这些 Issue".into(),
                none_block: "无".into(),
                none: "无".into(),
                claimed: "已认领".into(),
                unclaimed: "未认领".into(),
                pick_issue: "点一张 Issue".into(),
                recent_limit: "最近完成列张数".into(),
                recent_limit_help: "默认 5。只影响最右那一列。不能拖进这一列来关票。".into(),
                refresh_interval: "自动刷新间隔（秒）".into(),
                refresh_interval_help: "有人在看这块看板时，按这个间隔拉 Tracker。默认 300 秒，最短 15 秒，不设最大值。".into(),
                unclear_issue: "对端看不清".into(),
                refresh_now: "刷新".into(),
                refresh_refreshing: "正在刷新".into(),
                refresh_as_of: "数据截至".into(),
                refresh_next: "下次刷新".into(),
                refresh_offline: "已离线".into(),
                refresh_offline_recovery: "检查运行 Host 的电脑网络后点“刷新”重试。".into(),
                refresh_never: "还没有成功拉过 Tracker。".into(),
                refresh_rate_limited: "已被限流".into(),
                refresh_retry: "大约可再刷新".into(),
                refresh_paused: "自动刷新已暂停，可手动再试。".into(),
                refresh_auth: "凭据不可用".into(),
                refresh_auth_recovery: "在运行 Host 的电脑更新 GitHub 凭据后点“刷新”重试。".into(),
                refresh_incomplete: "数据不完整".into(),
                refresh_tracker_error: "Tracker 业务错误".into(),
                run_persistence_recovery_title: "Run 历史需要恢复".into(),
                run_persistence_recovery_body: "Host 无法可靠读取 runs.json。原文件已保留，所有会改写 Run 历史的操作已暂停。".into(),
                run_persistence_recovery_retry: "重试读取 Run 历史".into(),
                run_persistence_write_failed: "Host 无法保存 Run 历史变更。内存与磁盘仍使用原状态，请重试该操作。".into(),
                run_persistence_write_blocked: "Run 历史正处于恢复状态。请修复 runs.json 并重试读取，再修改 Run。".into(),
                new_run: "新建".into(),
                execute_run: "执行".into(),
                start_run: "启动".into(),
                start_run_pending: "启动中…".into(),
                switch_agent: "换一家".into(),
                pick_agent: "选择 Agent".into(),
                available_agents: "可用 Agent".into(),
                unavailable_agents: "不可用 Agent".into(),
                no_agent_selected: "尚未选择 Agent".into(),
                next_step: "下一步".into(),
                launch_title: "启动配置".into(),
                prefill_current: "预填来自这个 Project 上次成功启动，本次可改。".into(),
                prefill_other: "预填来自其它 Project 上这家 Agent 的记忆，本次可改。".into(),
                prefill_seed: "预填来自本机 CLI 种子，本次可改。".into(),
                isolation: "隔离执行目录".into(),
                isolation_off_reason: "为什么不可用".into(),
                isolation_hint: "机制是 git worktree。默认关，不记住。".into(),
                run_intent: "Run 意图".into(),
                intent_none: "不选".into(),
                intent_modify: "修改".into(),
                intent_continue: "继续".into(),
                intent_answer: "只回答".into(),
                intent_review: "复查".into(),
                intent_custom: "自定义".into(),
                opening_placeholder: "要 Agent 做什么".into(),
                folded_options: "附加参数与预览".into(),
                command_preview: "命令预览".into(),
                show_command_preview: "显示命令预览".into(),
                instruction_required: "请填写要 Agent 做什么。".into(),
                working_directory: "执行目录".into(),
                unbound_issue: "未绑定 Issue".into(),
                stop_run: "停止".into(),
                quit_active_title: "还有活跃 Run".into(),
                quit_active_body: "退出 Host 会停掉全部活跃 Run。选择返回则继续跑。".into(),
                quit_return: "返回".into(),
                quit_stop_all: "停掉全部".into(),
                view_changes: "查看改动".into(),
                focus_run: "聚焦".into(),
                open_issue: "浏览器打开".into(),
                search_title: "搜索 Issue".into(),
                search_placeholder: "按标题搜索，回车才查".into(),
                search_all_triage: "全部 triage".into(),
                search_all_states: "open / closed".into(),
                search_open: "open".into(),
                search_closed: "closed".into(),
                search_submit: "搜索".into(),
                keyboard_help: "键盘帮助".into(),
                this_round: "这一轮".into(),
                uncommitted: "未提交".into(),
                add_change_note: "写下改动备注".into(),
                change_note_placeholder: "一句话，下次开跑才带上".into(),
                delete_change_note: "删掉备注".into(),
                auto_advance: "自动推进".into(),
                auto_advance_help: "Host 总开关。还要在 Project 上打开才会领下一张 ready-for-agent。".into(),
                project_auto_advance: "这个 Project 自动推进".into(),
                restore_auto_advance: "冷启动后恢复自动推进".into(),
                restore_delay: "冷启动后等待秒数".into(),
                pending_confirmation: "待确认：即将领下一张 ready-for-agent".into(),
                veto_advance: "否决".into(),
                usage: "用量".into(),
                usage_hint: "这台 Host 上全部 Project 的 token 流水。不估美元，不管账号额度。".into(),
                host_overview: "总览".into(),
                host_overview_hint: "当前 Host 的 Project 态势与 Run；Run 按终端状态分组。".into(),
                host_overview_empty: "尚无通过 Agent Taskboard 启动的 Run；Project 态势仍在上方可见。".into(),
                return_to_board: "返回看板".into(),
                show_sidebar: "显示侧栏".into(),
                hide_sidebar: "收起侧栏".into(),
                show_issue_detail: "显示详情".into(),
                hide_issue_detail: "收起详情".into(),
                show_ended_runs: "显示已结束".into(),
                active_runs: "活跃 Run".into(),
                filtered_runs: "筛选后的 Run".into(),
                run_group_waiting: "等待操作".into(),
                run_group_running: "进行中".into(),
                run_group_stopped: "执行已停".into(),
                run_group_ended: "已结束".into(),
                range_24_hours: "24 小时".into(),
                range_today: "今天".into(),
                range_7_days: "7 天".into(),
                range_30_days: "30 天".into(),
                range_custom: "自定义".into(),
                filter_all: "全部".into(),
                filter_project: "Project".into(),
                filter_agent: "Agent".into(),
                filter_model: "模型".into(),
                token_input: "input".into(),
                token_output: "output".into(),
                token_cache_read: "cache read".into(),
                token_cache_write: "cache write".into(),
                token_reasoning: "reasoning".into(),
                token_total: "total".into(),
                ttft: "首字".into(),
                gen_rate: "生成速率".into(),
                cache_hit: "缓存命中".into(),
                spike: "偏慢".into(),
                proxy_disclaimer: "看板不管理 Clash 等节点。通路抖动时请到你自己的代理工具里换节点。".into(),
                open_host_usage: "Host 用量 ↗".into(),
                open_this_run: "打开此 Run 终端 ↗".into(),
                lane_main: "主会话".into(),
                lane_subagent: "子代理".into(),
                lane_switched: "已停用".into(),
                usage_empty: "这段时间没有 Run 用量。".into(),
                close_usage: "返回看板".into(),
                mobile_switch_scope: "切换范围".into(),
                mobile_board: "看板".into(),
                mobile_issue: "票".into(),
                mobile_run: "Run".into(),
                mobile_recent_output: "最近输出".into(),
                mobile_live_terminal: "打开活终端".into(),
                create_issue: "创建 Issue".into(),
                edit_issue: "编辑 Issue".into(),
                save_issue: "保存 Issue".into(),
                issue_title: "标题".into(),
                issue_body: "正文".into(),
                add_comment: "添加评论".into(),
                comment_placeholder: "写下评论".into(),
                parent_issue: "父 Issue".into(),
                dependency_blockers: "Blocked by（阻塞方）".into(),
                clear_dependency: "清除 Dependency".into(),
                save_relations: "保存关系".into(),
                close_issue: "关闭 Issue".into(),
                reopen_issue: "重新打开 Issue".into(),
                issue_updates: "评论与关系".into(),
                issue_conflict: "Tracker 中的同一内容已经变化。你的输入仍保留在表单中。".into(),
                issue_conflict_latest: "Tracker 最新值".into(),
                issue_conflict_use_latest: "载入最新值".into(),
                issue_conflict_overwrite: "仍然覆盖".into(),
    }
}
